### ISSUE TITLE
Uninformative Error in compRelSEM with multiple factors and ordered data

### ISSUE THREAD

**Issue by juliuspfadt** [simsem/semTools#130]
With the following data
[shortUpps.csv](https://github.com/simsem/semTools/files/12681459/shortUpps.csv)
and this code: 
```r
library(lavaan)

data <- read.csv("shortUpps.csv", sep = ";")
data <- data[complete.cases(data), ]

model <- "f1 =~ U17_r + U22_r + U29_r + U34_r
f2 =~ U4 + U14 + U19 + U27"

fit1 <- cfa(model, data, ordered = TRUE, std.lv = TRUE)
semTools::compRelSEM(fit1, tau.eq = FALSE, return.total = TRUE, ord.scale = TRUE)
```

I get the error: `Error in diag(scales) %*% truevar : non-conformable arguments`

It does not happen with a single factor: 
```r
model2 <- "f1 =~ U17_r + U22_r + U29_r + U34_r"

fit2 <- cfa(model2, data, ordered = TRUE, std.lv = TRUE)
semTools::compRelSEM(fit2, tau.eq = FALSE, return.total = TRUE, ord.scale = TRUE)
```
 
Given that the loadings and residuals are all there, and lavaan does not throw any warnings, I wonder what is going wrong?

**Comment by juliuspfadt** [comment]
Thanks for the swift reply. You are right, it is fixed. Thanks :)

**Comment by juliuspfadt** [comment]
Hi @TDJorgensen are there any news in regards to a CRAN version that contains the fix. Usually the JASP developers only allow CRAN packages so I can't really use your GitHub version.

**Comment by tomtomme** [comment]
@TDJorgensen 
Any news on the situation regarding a CRAN-Version of this package? Would be cool if we could report this as fixed for the upcoming JASP version 0.20 (possibly 1.0) in some months. Thx for the effort!

**Comment by TDJorgensen** [comment]
Sorry for the delay, but both `lavaan.mi` and the new `semTools` are now on CRAN.

**Comment by juliuspfadt** [comment]
cool!
