### ISSUE TITLE
Missing handling in mardiaSkew and mardiaKurtosis seems broken

### ISSUE THREAD

**Issue by juliuspfadt** [simsem/semTools#138]
I have a dataset with missings and the outputs of the functions are NA, except for the DF. 

```r
dt <- lavaan::HolzingerSwineford1939
dt <- dt[, 7:15]
dt[301, 1] <- NA
semTools::mardiaSkew(dt, use = "complete.obs")
semTools::mardiaKurtosis(dt, use = "complete.obs")
```
The option `use` suggests that one could handle missings, but I can only get results if I delete listwise before the analysis.

**Comment by TDJorgensen** [comment]
Thanks for reporting this! Sorry for the delay, this was posted when I was traveling across the Atlantic, after which I was prepping for the new semester. Finally catching up with some coding tasks I had on the back-burner.
