### ISSUE TITLE
measurementInvariance quiet argument boolean is wrong

### ISSUE THREAD

**Issue by psunthud** [simsem/semTools#15]
In the help file for the measurementInvariance function, I believe that the help file has the boolean action of the quiet argument reversed compared to actual behavior. Suggest changing 'if TRUE' to 'if FALSE' or rewriting the help file explanation to explain both states. The argument itself behaves as one would expect.

From avsfan733

**Comment by t129j179** [comment]
The argument's name and behavior are consistent and make sense.  I updated the help file to correct the description.
