### ISSUE TITLE
`reliability` method fails when some factors have only a single indicator

### ISSUE THREAD

**Issue by drpetersen** [simsem/semTools#17]
Hi, thanks a lot for all your work!

When using the `reliability` function on a CFA with some single-item factors, I get an error message (English translation along the lines of: "Error in trueitem + erritem : arrays don't match") which seems to come from the fact that the `diag` function returns a 0x0 matrix, instead of a 1x1 matrix, when its argument is a scalar instead of a 1x1 matrix, in lines 63–66 of `reliability.R`:

```
			truefac <- diag(faccontrib[index, index])
			commonfac <- sum(faccontrib[index, index])
			trueitem <- diag(truevar[index, index])
			erritem <- diag(te[[i]][index, index])
```

For me, the problem was fixed by adding the `drop = TRUE` option to the indexing operations:

```
			truefac <- diag(faccontrib[index, index, drop = TRUE])
			commonfac <- sum(faccontrib[index, index])
			trueitem <- diag(truevar[index, index, drop = TRUE])
			erritem <- diag(te[[i]][index, index, drop = TRUE])
```

As expected, the fixed `reliability` function returns reliabilites for the multiple-item factors and leaves out the single-item factors. I guess a similar fix might have to be applied in some other places, like in `reliabilityL2`.

Another question (sorry if this is documented somewhere, I simply couldn't find anything about it): What is the background for removing `ci.reliability`? Is there some substitute I haven't found yet, or was there a problem with the implementation, or was it just thought not to be useful anymore (I'm missing it `;-)`)?

Thank you for your time!

**Comment by t129j179** [comment]
Thanks for catching this.  I will add that update before the next version is released.

The developer (Sunthud Pornprasertmanit) moved `ci.reliability()` to the MBESS package.  Same function, but being maintained only there now, instead of in 2 different places.

**Comment by drpetersen** [comment]
Great, thanks!

**Comment by t129j179** [comment]
I added drop = FALSE to these lines and many others.  The changes are available on github, but note that the latest semTools requires the latest development version of lavaan.  New versions of both these packages will be submitted to CRAN within a week.
