### ISSUE TITLE
Equations do not render correctly for realiability function

### ISSUE THREAD

**Issue by jknowles** [simsem/semTools#19]
In the help/documentation file for the `reliability` function the equations do not render correctly. This is what I'm seeing on my most recent install of the development branch. 

![image](https://cloud.githubusercontent.com/assets/1310474/24531013/d4505dd8-1583-11e7-889b-efeaca78ece3.png)

Is this the same on other branches, or is this perhaps due to building from source and LaTeX being misconfigured?

**Comment by t129j179** [comment]
LaTeX math renders correctly in the PDF

https://cran.r-project.org/web/packages/semTools/semTools.pdf

Only simple aspects of LaTeX math (e.g., Greek symbols, but not fancy displays like fractions or sums) render correctly in the HTML help pages:

https://stat.ethz.ch/pipermail/r-help/2008-August/171907.html
