### ISSUE TITLE
Save file as csv?

### ISSUE THREAD

**Issue by ckraner** [simsem/semTools#21]
It would be very convenient to be able to use savefile() and have it output a comma-delimited file, or even a tab-delimited file. I want to use this to import tables into LaTeX, as well as eventually display this table in the R-Studio viewer, and this would make things much easier.

Love the package!

**Comment by t129j179** [comment]
Thanks, and good idea.  You could already save as tab-delimited file using the argument `tableFormat = TRUE`, but I just added a `writeArgs` argument so you can pass more arguments to `write.table()`.  Following from the examples on the help page, try this:

``` {r}
saveFile(fit, "out.txt", "mifit", tableFormat = TRUE)
```

If you install the latest development version of semTools (0.4-15.907), you can try the CSV option.

``` {r}
devtools::install_github("simsem/semTools/semTools")
saveFile(fit, "out.csv", "mifit", tableFormat = TRUE, writeArgs = list(sep = ","))
```

You should be able to open "out.csv" in Excel or LibreOffice-Calc and see a nicely delimited table.
