### ISSUE TITLE
Issue with using rank instead of order when comparing variables in datasets

### ISSUE THREAD

**Issue by michaelhallquist** [simsem/semTools#26]
I recently bumped into an error using the net() function on two models I knew were run on the same data, but I received the error:  "Models must apply to the same data." Looking at the source https://github.com/simsem/semTools/blob/master/semTools/R/NET.R, at line 240, there is a check on whether the data analyzed match between models (though it's commented out on Github). This code uses the rank function to order the dataset analyzed by lavaan, presumably to ensure equivalent variable ordering. The problem is that I believe order(), not rank(), should be used. Rank returns the wrong values for some names:

> rank(c("Y", "M", "X"))
[1] 3 1 2

whereas order gives the expected result:
> order(c("Y", "M", "X"))
[1] 2 3 1

I see that this code has been commented out, and reinstalling the package seems to now skip over this issue (perhaps my version was out of date?). Regardless, I wanted to pass along this suggestion in case it helps to reinstate this check on the model data.

Best,
Michael

**Comment by TDJorgensen** [comment]
Hi Michael,
You're right, I commented that out so I could think of a fix later, so the current development version does not do the check.  But your simple solution will probably work fine.  I'll add it to my next commit. 
Thanks for the suggestion,
Terrence

**Comment by TDJorgensen** [comment]
Finally have time for programming, so I have made this change and re-instated check the data for consistency.  Thanks again for the suggestion!
