### ISSUE TITLE
reliabilityL2() without reference

### ISSUE THREAD

**Issue by jorgesinval** [simsem/semTools#35]
Can someone provide a reference of published paper regarding the realibilityL2 (L1, L2, L1 partial) estimates? Otherwise, I will have to cite the semTools package itself.

**Comment by TDJorgensen** [comment]
These showed up on the first page of a Google search for "omega reliability higher order factor", so you might be able to turn up more with a deeper search or looking through their reference list:

http://mjesec.ffzg.hr/revija.psi/vol%2021%20no%202%202014/Wahyu%20Widhiarso%201.pdf

http://personality-project.org/revelle/publications/zinbarg.revelle.pmet.05.pdf

They discuss hierarchical omega, but I don't know specifically about the partial vs. others.  Not sure what reference Sunthud had read when he wrote this function, but the differences are just a matter of what is in the numerator and what is in the denominator.  Are you asking how much of the total observed variance is explained (L1, L1-partial) or how much of the first-order factor variance is explained (L2) by the higher-order factor?  If the former, are you asking how much is explained by all factors (L1) or uniquely by the higher-order factor (L1-partial)?  

It's similar to expressing multiple types of ICC at each level of analysis when you have more than 2 levels (e.g., students nested in classes nested in schools): You can ask how much class variance is explained by school differences (like L2), or how much student variance is explained by school _and_ class differences (like L1), or how much student variance is explained by either school or class differences alone (like L1-partial).

If you decide to cite the package, there will be a new version on CRAN soon, with updated `citation("semTools")` output.

**Comment by jorgesinval** [comment]
Thanks! I think that I will opt for the semTools citation, I used it already in my publications. So there will be no more "semTools Contributors" as authors? I saw that the citation now suggests to you, Pornprasertmanit, Schoemann, and Rosseel.

**Comment by TDJorgensen** [comment]
Yes, I felt that "semTools contributors" unfairly equated the level of contributions between authors/maintainers and occasional outside contributions (which are **very much appreciated**, but often need further revision by maintainers before inclusion in semTools).  All contributors are still listed in the `DESCRIPTION` page, on [CRAN](https://cran.r-project.org/web/packages/semTools/), and on the semTools [wiki](https://github.com/simsem/semTools/wiki/Developers).
