### ISSUE TITLE
Error using htmt function

### ISSUE THREAD

**Issue by cnlowell** [simsem/semTools#38]
When I run the example provided on RDocumentation (as well as my personal application that previously worked) I receive the following error:

```
Error in lavParseModelString(model.syntax = model, warn = warn, debug = FALSE) : 
  lavaan ERROR: model does not contain lavaan syntax (no operators found)
```

Do you know if this is a bug or can you help me understand the error?
The example code is listed below:

 ```
HS.model <- ' visual  =~ x1 + x2 + x3
              textual =~ x4 + x5 + x6
              speed   =~ x7 + x8 + x9 '

dat <- HolzingerSwineford1939[, paste0("x", 1:9)]
htmt(dat, HS.model)

```
Thank you!

**Comment by TDJorgensen** [comment]
Have you updated your software (semTools 0.5-0, lavaan 0.6-2) and tried again in a fresh workspace?  This does not return an error for me, but works as expected.

**Comment by cnlowell** [comment]
Yes, I have the most recent versions of semTools and lavaan. I even tried uninstalling and re-installing R. Strange. Thank you for your response!
