### ISSUE TITLE
fitMeasures.mi additional arguments

### ISSUE THREAD

**Issue by maugavilla** [simsem/semTools#46]
Hi

When I am working with ordered items, fitMeasures does not let me add additional arguments like: test="D2, pool.robust=T

The default gives me the indices with the message:
> fitMeasures(fit_pvpe)
"D3" only available using maximum likelihood estimation. Changed test to "D2".
Robust corrections are made by pooling the naive chi-squared statistic across 100 imputations for which the model converged, then applying the average (across imputations) scaling factor and shift parameter to that pooled value. 
To instead pool the robust test statistics, set test = "D2" and pool.robust = TRUE. 

But it does not recognize the test and pool.robust arguments
> fitMeasures(fit_pvng,test = "D2", pool.robust = TRUE)
Error in .local(object, fit.measures, baseline.model, ...) : 
  unused arguments (test = "D2", pool.robust = TRUE)
> semTools::fitmeasures(fit_pvng,test = "D2", pool.robust = TRUE)
Error in .local(object, fit.measures, baseline.model, ...) : 
  unused arguments (test = "D2", pool.robust = TRUE)
> semTools:::fitMeasures.mi(fit_pvng,test = "D2", pool.robust = TRUE)
Error in semTools:::fitMeasures.mi(fit_pvng, test = "D2", pool.robust = TRUE) : 
  unused arguments (test = "D2", pool.robust = TRUE)

Thank for all the work on this package

**Comment by TDJorgensen** [comment]
Thanks for catching this.  I had to wait for Yves to put `...` into `fitMeasures()` for this to work, then I forgot about it.  Your code should work now (also via `compareFit()`, if you use that).
```
devtools::install_github("simsem/semTools/semTools")
```
