### ISSUE TITLE
Error while using residuals() function on lavaan.mi object

### ISSUE THREAD

**Issue by david-vas** [simsem/semTools#47]
When I try to obtain the residuals matrix of lavaan.mi object using the residuals() function, I get an error stating:

Error in gp.resid.lavaan.mi(Observed = object@SampleStatsList[useImps],  : 
  object 'N' not found

Tried it on different lavaan.mi objects, didn't work. Nor with the resid() function.

**Comment by TDJorgensen** [comment]
I think I resolved this problem already.  Can you try it with the development version?
```
devtools::install_github("simsem/semTools/semTools")
```
If it persists, can you send me a script that reproduces the problem, either with the help-page data or your own?  The models on the help page work for me (both single- and multigroup examples).

**Comment by david-vas** [comment]
True! Works fine with the development version. Thank you very much.
