### ISSUE TITLE
Integrate imposeStart and monteCarloMed

### ISSUE THREAD

**Issue by lingchuding** [simsem/semTools#49]
Dear Dr. Jorgensen,

I find the semTools package is useful since it provides many functions to nudge the analyses of SEM. And I am wondering whether I can integrate imposeStart and monteCarloMed to calculate the indirect effect and its confidential interval from the 1-1-1 model automatically. 

Though both the monteCarloMed function in your package and the online utilities provided by Preacher is powerful, usually I feel troublesome to find out and input those parameters necessary for the Monte Carlo estimating. Would you please give me some suggestions about how to do this in a more automatic way? Many thanks!

**Comment by TDJorgensen** [comment]
I don't see how `imposeStart()` would help, but you can extract the information you need from a lavaan model to pass to `monteCarloMed()`.  Working with the [tutorial](http://lavaan.ugent.be/tutorial/mediation.html) example:

```
set.seed(1234)
X <- rnorm(100)
M <- 0.5*X + rnorm(100)
Y <- 0.7*M + rnorm(100)
Data <- data.frame(X = X, Y = Y, M = M)
model <- ' # direct effect
             Y ~ c*X
           # mediator
             M ~ a*X
             Y ~ b*M
           # indirect effect (a*b)
             ab := a*b
           # total effect
             total := c + (a*b)
         '
fit <- sem(model, data = Data)
coef(fit) # all parameters
vcov(fit) # asymptotic covariances among all parameters
```

You can extract your labeled parameters (here, `a` and `b`) 

```
myParams <- c("a","b")
coef(fit)[myParams]
vcov(fit)[myParams, myParams]
```

and pass them to `monteCarloMed()`

```
monteCarloMed('a*b', coef(fit)[myParams],
              ACM = vcov(fit)[myParams, myParams])
```

Notice how similar the CI is to the one derived from the delta method:

```
summary(fit, ci = TRUE)
```
 
But Monte Carlo CIs should work better in smaller samples.

The same principles apply in a multilevel (or any) lavaan model:  Label your direct effects so you can use those labels to calculate indirect effects and their CIs in the `monteCarloMed()` function.  I will make a note to add this example to the `?monteCarloMed` help page.

**Comment by TDJorgensen** [comment]
A concise version of the example above is now available on the `?monteCarloMed` help page in the development version.

```
devtools::install_github("simsem/semTools/semTools")
```

Thanks for the suggestion.
