### ISSUE TITLE
Probable calculation error for SRMR with runMI

### ISSUE THREAD

**Issue by perlus** [simsem/semTools#58]
Hej everyone,
Thank you so much for all the work on lavaan and semTools.

I am not sure if the following issue is related to semTools or lavaan.

After having issues with running runMI I installed the dev Version of semTools as proposed by Terrence. Most everything is working fine. But, I am always getting a 0.000 for the SRMR, where I got a 0.043 before when estimating on pooled data with lavaan.survey.

I would be glad to help out with any other information to track down the "issue".

Kind regards from Germany
Alex

**Comment by TDJorgensen** [comment]
Thanks for catching this Alex.  I found the silly little mistake (which only happened with single-group, single-level models) and fixed it in the development version (0.5-1.918).
