### ISSUE TITLE
error message in fitmeasures "srmr" in lavaan.mi

### ISSUE THREAD

**Issue by dgnhatun** [simsem/semTools#61]
I am having an error message for "srmr" fitmeasure. 

Without the "srmr" option, I do not have any error message.

My codes:
#imputation
hway_imp<-mice(data, m = 5, seed = 12435)
mice.imp5 <- NULL
for(i in 1:5) mice.imp5[[i]] <- complete(hway_imp, action=i, inc=FALSE)

#model and fit measures
latent1 <- 'Neigh =~ var1+ var2 + var3 + var4'
out1 <- runMI(latent1,
data=mice.imp5,
fun="cfa",
meanstructure = TRUE)
summary(out1)
fitMeasures(out1, c("chisq", "df", "pvalue", "cfi", "tli", "rmsea", "srmr"))

#error message

fitMeasures(out1, c("chisq", "df", "pvalue", "cfi", "tli", "rmsea", "srmr"))
Error in gp.resid.lavaan.mi(Observed = object@SampleStatsList[useImps], :
object 'N' not found
BUT,

When I run "runMI" with group = "gender", I can see SRMR result without any error message (I am also not sure if it is okay to use group option this way).

latent1 <- 'Neigh =~ var1+ var2 + var3 + var4'
out1 <- runMI(latent1,
data=mice.imp5,
fun="cfa",
meanstructure = TRUE, group = "gender")
summary(out1)
fitMeasures(out1, c("chisq", "df", "pvalue", "cfi", "tli", "rmsea", "srmr"))

#results

fitMeasures(out1, c("chisq", "df", "pvalue", "cfi", "tli", "rmsea", "srmr"))

chisq df pvalue baseline.chisq baseline.df baseline.pvalue cfi tli rmsea
4.792 4.000 0.309 993.641 12.000 0.000 0.999 0.998 0.020
rmsea.ci.lower rmsea.ci.upper rmsea.pvalue srmr
0.000 0.073 0.771 0.010

How can I solve this error problem? Thanks

**Comment by TDJorgensen** [comment]
I thought I replied to this ages ago.  This error was long ago resolved.  Try installing the development version:

```
devtools::install_github("simsem/semTools/semTools")
```
You will need to install the latest lavaan first:

```
install.packages("lavaan", repos = "http://www.da.ugent.be", type = "source")
```

**Comment by TDJorgensen** [comment]
I assume this was resolved.
