### ISSUE TITLE
semTools installed but it can't be loaded

### ISSUE THREAD

**Issue by matguidi** [simsem/semTools#68]
I have installed semTools from github with the command

`devtools::install_github("simsem/semTools/semTools")`

The installation concludes without error messages, but when I try to load the package in an R session I get the following error message:

`Function found when exporting methods from the namespace ‘semTools’ which is not S4 generic: ‘anova’`

and the package doesn't load.

I am running R version 3.6.2 (2019-12-12) -- "Dark and Stormy Night". Every other package loads just fine.

**Comment by matguidi** [comment]
I solved by running
`remove.packages(semTools)`
and then
`install.packages("semTools", dependencies = T)`

**Comment by TDJorgensen** [comment]
Restarting R after using `devtools::install_github()` is always a good idea too, as well as calling it only in a fresh R session so nothing is yet attached beyond the base packages.  That may have avoided the need to remove the old version. Glad it worked out.
