### ISSUE TITLE
reliability and maximalRelia doesnt work with ordered indicators

### ISSUE THREAD

**Issue by maugavilla** [simsem/semTools#71]
A user share this issue and I replicate it, when the indicators are binary, the functions reliability and maximalRelia show an error 
Error: $ operator not defined for this S4 class

I tried to find the issue in the code, but couldnt find the solution

Here is code that shows the error

library(lavaan)
library(semTools)

dat <- HolzingerSwineford1939
summary(dat)
dat <- apply(HolzingerSwineford1939[,paste0("x",1:3)], 2, cut, breaks = c(2), labels = FALSE)

HS.model <- ' visual  =~ x1 + x2 + x3'

fit <- cfa(HS.model, std.lv=T, data = dat, estimator="wlsmv",
           ordered=paste0("x",1:4))
summary(fit, fit.measures = TRUE)

reliability(fit)
maximalRelia(fit)

**Comment by TDJorgensen** [comment]
I think this is an old issue already resolved. Does it replicate in the development version?

**Comment by maugavilla** [comment]
Oh, yes it worked well with the development version semTools_0.5-2.920

Just pasted the solution in the google group thread

thanks
