### ISSUE TITLE
Unable to get fit measures for lavaan.mi objects

### ISSUE THREAD

**Issue by rewildered** [simsem/semTools#72]
Thank you Terrence and all the contributors for your work on this awesome package! 

I am running a CFA model for a dataset with missing values using the runMI function and imputing the missing values on the fly using the Amelia package. When I try to get fit measures using *summary(myfittedobject, fit.measures = TRUE)*, I get the following error: >Error in .local(object, ...) : unused argument (fit.measures = TRUE)

This happens with both the latest development version (0.5-2.920) and the stable version. I thought something might be wrong with my setup or data, but then I noticed the same error happens when I run the example file (https://rdrr.io/cran/semTools/man/runMI.html) either locally or in the browser. 

Any ideas on what might be causing this?

**Comment by TDJorgensen** [comment]
As the message says, that is not an argument for the method written for this class of object. See the `class?lavaan.mi` for the arguments you can pass to its `summary()` method, which essentially does what `parameterEstimates()` does for lavaan objects.  You can get fit measures from the `fitMeasures()` method.
