### ISSUE TITLE
Self defined parameter missing after measEq.syntax 

### ISSUE THREAD

**Issue by emailyc** [simsem/semTools#73]
Self defined parameters are omitted by lavaan model generated by measEq.syntax

```
HS.model <- 
"visual =~ x1 + a*x2 + x3;
textual =~ x4 + b*x5 + x6;
speed =~ x7 + x8 + x9; 

visual ~ a*speed +  b* textual; 

#defined parameter
ab:=a*b;"

fit <- cfa(HS.model,data = HolzingerSwineford1939,group = "school",  auto.fix.first=TRUE)
invariance = measEq.syntax(configural.model = fit, ID.fac = "auto.fix.first", group.equal = "loadings", return.fit = TRUE)
```

> tail(parameterEstimates(fit))
       lhs op rhs block group label   est    se      z pvalue ci.lower ci.upper
68      x8 ~1         2     2       5.488 0.087 63.174  0.000    5.318    5.659
69      x9 ~1         2     2       5.327 0.085 62.571  0.000    5.160    5.494
70  visual ~1         2     2       0.000 0.000     NA     NA    0.000    0.000
71 textual ~1         2     2       0.000 0.000     NA     NA    0.000    0.000
72   speed ~1         2     2       0.000 0.000     NA     NA    0.000    0.000
73      ab := a*b     0     0    ab 0.214 0.067  3.190  0.001    0.083    0.346

> tail(parameterEstimates(invariance))
       lhs op     rhs block group      label   est    se     z pvalue ci.lower ci.upper
71  visual ~~  visual     2     2 psi.1_1.g2 0.411 0.116 3.542  0.000    0.184    0.639
72 textual ~~ textual     2     2 psi.2_2.g2 0.906 0.136 6.646  0.000    0.639    1.173
73   speed ~~   speed     2     2 psi.3_3.g2 0.475 0.109 4.347  0.000    0.261    0.690
74  visual ~~ textual     2     2 psi.2_1.g2 0.000 0.000    NA     NA    0.000    0.000
75  visual ~~   speed     2     2 psi.3_1.g2 0.000 0.000    NA     NA    0.000    0.000
76 textual ~~   speed     2     2 psi.3_2.g2 0.226 0.072 3.144  0.002    0.085    0.367

**Comment by TDJorgensen** [comment]
This is a feature, not a bug.  I cannot simultaneously honor self-defined parameter labels and guarantee that the requested identification constraints are imposed using parameter labels.  For example, you specified a single label for 2 factor loadings in a multigroup model, so your custom labels only apply to the first group, and they would not match the systematically generated labels in group 2 in order to constrain factor loadings as requested.

You are welcome to copy/paste the generated syntax into your own script to edit by choosing your own labels.  If you have the latest development version installed, you could also use the `update()` method to change any labels in the `measEq.syntax` object.  Working from your example:

```
HS.model <- "
visual =~ x1 + x2 + x3
textual =~ x4 + x5 + x6
speed =~ x7 + x8 + x9

# LATENT REGRESSIONS ARE NOT ACKNOWLEDGED
# (unless they are higher-order factor loadings)
# BECAUSE THIS WOULD NO LONGER BE A CFA MODEL,
# visual ~ a*speed +  b* textual

# defined parameter; THIS CAN BE ADDED POST HOC BY HACKING
#         THE MECHANISM I USE TO ADD CONSTRAINTS TO SYNTAX
# ab:=a*b;
"

invariance <- measEq.syntax(HS.model, data = HolzingerSwineford1939,
                            ID.fac = "auto.fix.first",
                            group = "school", group.equal = "loadings")
newInv <- update(invariance, 
                 change.syntax = c("visual  =~ c(a, a)*x2",
                                   "textual =~ c(b, b)*x5"))

## add user-defined parameters to the @constraints slot,
## which simply adds any additional syntax to a script
newInv@constraints <- c(newInv@constraints, "ab := a*b")

## verify
cat(mod.metric <- as.character(newInv)) # print syntax first
fit.metric <- cfa(mod.metric, data = HolzingerSwineford1939, group = "school")
summary(fit.metric)
```
