### ISSUE TITLE
First order factors being treated as second order factors in a model with only one second order factor

### ISSUE THREAD

**Issue by ktmanis** [simsem/semTools#84]
> ########CFA MODEL FOR SECOND-ORDER FACTOR########
> #SPECIFY MODEL
> CFA.JAIS.20 <-
+   '
+ # SPECIFY FIRST-ORDER FACTORS#
+
+ SV =~ SV2 + SV3 + SV4
+ CG =~ CG2 + CG3 + CG4
+ RI =~ RI2 + RI3 + RI4
+ TRU =~ TRU1 + TRU2 + TRU5
+ COM =~ COM3 + COM4 + COM5
+ KI =~ KI1 + KI2 + KI4
+ KEX =~ KEX3 + KEX4 + KEX6
+ CK =~ CK2 + CK3 + CK5
+ SDC =~ EK2 + EK4 + EK5
+ CR =~ CR1 + CR2 + CR3
+ OP =~ OP1 + OP2 + OP3
+ MP =~ MP2 + MP3 + MP4
+
+ # SPECIFY SECOND-ORDER FACTORS#
+ IC=~1*KI+1*KEX+1*CK
+ IC~~IC
+
+ #RESIDUALS - THESE ARE DETERMINED THROUGH MODIFICATION INDICES -  modindices()#
+ MP2 ~~  MP4
+ CG2 ~~  CG4
+ EK4 ~~  EK5
+ KI1 ~~  KI4
+ RI2 ~~  RI4
+ OP1 ~~  OP2
+ KEX3 ~~ KEX4
+ '
> reliability(fit.CFA.20)
Higher-order factors were ignored.

              KI       KEX        CK
alpha  0.6849464 0.8872550 0.7818604
omega  0.8152728 0.8071967 0.8004426
omega2 0.8152728 0.8071967 0.8004426
omega3 0.8422551 0.7122995 0.8631846
avevar 0.5096021 0.6484720 0.5728214
> reliabilityL2(fit.CFA.20, "IC")
       omegaL1        omegaL2 partialOmegaL1
     0.7461249      0.8237391      0.8849996
> reliabilityL2(fit.CFA.20, "OP") ##first-order factor being treated as second-order
       omegaL1        omegaL2 partialOmegaL1
     0.6768584      0.6768584      0.6768584

**Comment by TDJorgensen** [comment]
You need to put backticks around your syntax if you want to format your syntax example.
Bug now fixed in development version.
