### ISSUE TITLE
prob* series with labels for regression paths

### ISSUE THREAD

**Issue by schoam4** [simsem/semTools#88]
The probe* series of functions will provide an error when paths from the predictors to the outcomes use labels. The error message says "Error in varEst[targetcol, targetcol] : subscript out of bounds" The issue is that lavaan uses labels in vcov() instead of full terms for the parameters so when we try to pull the parameters we need those are missed (e.g. line 249). We probably need to pull from the ACM of the model itself (e.g. fit@vcov).

**Comment by TDJorgensen** [comment]
Well, this took a day of productivity.  While fixing this, I also found a bug (as opposed to an undocumented limitation in the source code).  With multigroup models, it would retrieve the group-2 estimates but still use the group-1 *SE*s.  Both issues are now resolved in 0.5-4.910
