### ISSUE TITLE
examples not working on compareFit function

### ISSUE THREAD

**Issue by awmeade** [simsem/semTools#90]
With recent updates to the compareFit function, the examples no longer produce any output.  I believe you now need to save the results of compareFit to an object and then run summary() on this object.  The examples have not been updated and just running compareFit does not produce any observable output.  
SemTools version 0.50-4.

**Comment by TDJorgensen** [comment]
Thanks for noticing this Adam, you weren't the first.  This was just resolved in the development version, so the `show()` method will print a message telling users to save the object and use `summary()`, and the documentation and examples have been updated.

```
devtools::install_github("simsem/semTools/semTools")
```

This resolves the original unwanted result of printing to the screen even when assigning `compareFit()` output to an object.  Only `summary()` does that, as Sunthud originally designed it similar to lavaan's `summary()` method.

**Comment by awmeade** [comment]
Thanks and great work on the package!  I really enjoy using it in both my research and classes.
