### ISSUE TITLE
using reliability for multiple groups with ordered variables

### ISSUE THREAD

**Issue by abramczuk** [simsem/semTools#91]
I love semTools package a lot.
However, recently I came across a problem.
It seems impossible to compute reliability estimates when you simultaneously have
1. grouped analysis
2. ordered measurement
Each separately works just fine. However when put together the software returns a threshold error.

**Comment by TDJorgensen** [comment]
Try installing the development version:
```
devtools::install_github("simsem/semTools/semTools")
```

This example has both features and works fine:
```
fit <- cfa('f1 =~ u1 + u2 + u3 + u4 ; f2 =~ u5 + u6 + u7 + u8',
           data = datCat, group = "g")
reliability(fit)
```

**Comment by abramczuk** [comment]
This worked like a charm.
Thank you!
