### ISSUE TITLE
Using probe2wayRC() function, but showing error pertaining to probe2wayMC()

### ISSUE THREAD

**Issue by HarmanjitS** [simsem/semTools#92]
I used following code as part of moderation analysis:
 
result2WayRC <- probe2WayRC(fit, nameX = c("Ad","Fed","AdXFed"), nameY = "Pon", modVar = "Fed", valProbe = c(-1,0,1))

It showed following error:
Error: The probe2WayMC() function requires the model to be fit with a mean structure.

NOTE: Why it is showing error related to a function different than called for?

**Comment by schoam4** [comment]
What version of semTools are you using? In the current version the error should read "This function requires the model to be fit with a mean structure" If you want to use probe2WayRC you will need to refit the model with a mean structure (the means are needed in the calculations of the simple slopes with residual centering).

Alex

**Comment by HarmanjitS** [comment]
@schoam4 I am using semTools 0.5-4
Problem here is that I am calling upon  probe2WayRC() function (as I am using the residual centering approach for moderation analysis); while the error being showcased is for probe2WayMC() function, which I am not even calling in the syntax. Is there any way out?

**Comment by TDJorgensen** [comment]
Visit the Wiki to see the syntax for installing the latest development
version--

Terrence D. Jorgensen
Assistant Professor, Methods and Statistics
Research Institute for Child Development and Education, the University of
Amsterdam
http://www.uva.nl/profile/t.d.jorgensen

**Comment by HarmanjitS** [comment]
@TDJorgensen I don't understand how to install syntax which is under development. Please guide.

**Comment by schoam4** [comment]
The wiki can be found here: https://github.com/simsem/semTools/wiki see the section on Installation and use the instructions for installing with the devtools package.

The error you got is a typo in the version of semTools. The bigger issue with your analysis is that you need to fit your model with a mean structure before probing. See this page for details on including a mean structure with lavaan: https://lavaan.ugent.be/tutorial/means.html

**Comment by HarmanjitS** [comment]
Thanks Alexander,

Just adding the argument meanstructure = TRUE in the fitting function
solved my problem. Did not require installing the under development
package. Thanks for guiding me.
